### PR TITLE
Port to 1.20.1

### PR DESCRIPTION
**Pull request by VoidLeech**
Hi! I'm the author of [Paths are Roads](https://github.com/VoidLeech/Paths-Are-Roads) and in the process of porting that to versions other than 1.20.1, I came across your mod, which I'd like to provide native compatibility for.
Imagine my sadness then to see it not updated to the latest versions that Undergarden *has* been ported to. 

So I've just spent an evening porting it as that seemed very manageable :D
I'm aware your license would just permit me to release the ports, but I'd love to just contribute them back to you (and could we see a modrinth release as well then?). I obviously don't *want* to PR against the existing branches but that should be fixable if you would create new branches for 1.20.1, 1.20.4, and 1.20.6.

**Significant changes:**
- All built for Neoforge as Undergarden itself is on Neoforge:
  - Neoforge's refactors past 1.20.1
  - build.gradle and gradle.properties are mostly (re)constructed from the Neoforge MDK
  - Gradlew/gradlew.bat changes are pulled from the Neoforge MDK
- Adding to the creative menu has to happen via event now
- Datagen passes around a PackOutput object instead of a DataGenerator.
- 1.20.6 uses java 21

**Concerns:**
- 1.20.6 is still only on a beta version of Neoforge

### CODE REVIEW

**Comment by VoidLeech** [comment]
Hi, for full transparency, I've made projects for these ports on Curseforge and Modrinth (under review at the moment). You are still properly credited everywhere of course. 
If/when these PRs get merged (or if you decide to port it yourself) I'll archive the projects, since a project of yours should always be the preferred one in my opinion.
The only differences between the releases and the PR versions is that the releases point to the issue tracker on my fork, and with that and the porting effort I've added myself to the authors in gradle.properties/mods.toml

Let me know in what capacity (if any) you'd like to be added (as a member) to these projects if you get to reading this (:

**Comment by Xaidee** [comment]
I've been meaning to port this mod to 1.20 plus, did start on a local branch but was yet to finish. If you'd like I can merge this PR and add you to the original CurseForge and Modrinth pages as a co-author as well as this GitHub if you'd like

**Comment by Xaidee** [comment]
I'll look at and review this PR tomorrow when I'm at my PC but in the meantime feel free to find my on Discord and message me if you want to discuss this more

**Comment by VoidLeech** [comment]
> I've been meaning to port this mod to 1.20 plus, did start on a local branch but was yet to finish. If you'd like I can merge this PR and add you to the original CurseForge and Modrinth pages as a co-author as well as this GitHub if you'd like

Getting the PR merged (or the mod updated) was the end goal, so that'd be great. I'd set up the projects just to actually get it out  there, and maintain the fork in absence of the PRs getting merged,  though I'd love to pick up a more permanent maintainer role looking forward. (As an aside, there currently is no original Modrinth page)

> I'll look at and review this PR tomorrow when I'm at my PC but in the meantime feel free to find my on Discord and message me if you want to discuss this more

Awesome! I'll open up that channel for communication, to discuss the above at the very least (:

**Pull request merged**
